// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWEBFinal.Infrastructure;

#nullable disable

namespace NWEBFinal.Infrastructure.Migrations
{
    [DbContext(typeof(NWebFinalDbContext))]
    partial class NWebFinalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NWEBFinal.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId");

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Students_DateOfBirth_Past", "[DateOfBirth] < CAST(GETDATE() AS date)");
                        });

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Hà Nội",
                            DateOfBirth = new DateOnly(2000, 1, 1),
                            Email = "vana@example.com",
                            FullName = "Nguyễn Văn A",
                            PhoneNumber = "0901111222"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "TP.HCM",
                            DateOfBirth = new DateOnly(2001, 2, 2),
                            Email = "thib@example.com",
                            FullName = "Trần Thị B",
                            PhoneNumber = "0902222333"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "Đà Nẵng",
                            DateOfBirth = new DateOnly(1999, 3, 3),
                            Email = "vanc@example.com",
                            FullName = "Lê Văn C",
                            PhoneNumber = "0903333444"
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "Cần Thơ",
                            DateOfBirth = new DateOnly(2002, 4, 4),
                            Email = "thid@example.com",
                            FullName = "Phạm Thị D",
                            PhoneNumber = "0904444555"
                        },
                        new
                        {
                            StudentId = 5,
                            Address = "Hải Phòng",
                            DateOfBirth = new DateOnly(2000, 5, 5),
                            Email = "vane@example.com",
                            FullName = "Hoàng Văn E",
                            PhoneNumber = "0905555666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
